### ISSUE TITLE
Select multiple tags

### ISSUE THREAD

**Issue by majkinetor** [ksdev-pl/Gist-List#1]
Hello

First, this tool is epic - I appreciate your efforts to have everything in the file system and not having dependency on the databases and other things. 

Now to the issue - unless I am mistaken, you can't search by multiple tags which is rather limiting (that is, to have AND/OR search capabilities).  Is there any chance for this to get added ?

**Comment by ksdev-pl** [comment]
Hello

Thanks. I will look into it in soon.

**Comment by ksdev-pl** [comment]
This was an embarrassingly slow "soon"... (a81ddca7f1f3e697d23438e55e027eaf11fa5536) 

I'm sorry for not keeping my word, life happened.

**Comment by majkinetor** [comment]
Heh, no problem :) It counts that you eventually did :)
