### ISSUE TITLE
Support tags with '-' between words.

### ISSUE THREAD

**Issue by majkinetor** [ksdev-pl/Gist-List#3]
Enough said.

PS: btw, latest version is MUCH faster. Thanks for great work.

**Comment by ksdev-pl** [comment]
Done: https://github.com/ksdev-pl/Gist-List/commit/f2de2333585a05c418f447d5301c0c0d5864dc8d

I am glad that it is faster :)

**Comment by majkinetor** [comment]
Awesome, thx a lot :1st_place_medal:
