### ISSUE TITLE
Tag feature not working as expected

### ISSUE THREAD

**Issue by JustinMcNamara74** [ksdev-pl/Gist-List#5]
I've noticed the tag feature hasn't been working consistently. Some tags that were working previously, are no longer being recognized.

Here are some examples where the tags are not working:
[#Netezza](https://gist.github.com/JustinMcNamara74/8041a73b92d14905039a3c2f775fef9d)
[#Bash](https://gist.github.com/JustinMcNamara74/af14565af0aa5cc966fa)
[#MSSQL](https://gist.github.com/JustinMcNamara74/43071d02ce99680dcd5c)

**Comment by ksdev-pl** [comment]
Hi,

I've added the possibility of tags at the beginning of the string: https://github.com/ksdev-pl/Gist-List/commit/32d1850fcf1c53b3fc036d005fbdca2813357274

**Comment by JustinMcNamara74** [comment]
Thank you very much!
